"""initial server schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-17 23:42:44.846316
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('sprint_id', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('labels_json', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('external_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backlog_item_type', 'backlog_items', ['item_type'], unique=False)
    op.create_index('idx_backlog_project_id', 'backlog_items', ['project_id'], unique=False)
    op.create_index('idx_backlog_sprint_id', 'backlog_items', ['sprint_id'], unique=False)
    op.create_index('idx_backlog_status', 'backlog_items', ['status'], unique=False)
    op.create_table('client_events',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('source_row_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('client_updated_at', sa.Text(), nullable=False),
    sa.Column('received_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'event_id')
    )
    op.create_table('learning_consent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('user_object_id', sa.Text(), nullable=True),
    sa.Column('consent_given', sa.Integer(), nullable=False),
    sa.Column('consented_at', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('learning_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Text(), nullable=False),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('context_type', sa.Text(), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_index('idx_learning_samples_context', 'learning_samples', ['context_type'], unique=False)
    op.create_index('idx_learning_samples_email', 'learning_samples', ['user_email'], unique=False)
    op.create_table('learning_sync_state',
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('last_collected', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('learning_user_profiles',
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.Text(), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('acted_at', sa.Text(), nullable=True),
    sa.Column('acted_by', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_seen_events',
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('event_key', sa.Text(), nullable=False),
    sa.Column('seen_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'event_key')
    )
    op.create_table('platform_sync_cache',
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'item_id')
    )
    op.create_table('platform_sync_meta',
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('last_sync', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('pm_update_queue',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('update_json', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.Text(), nullable=False),
    sa.Column('processed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('template_type', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('budget_estimate', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('risk_description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('external_source', sa.Text(), nullable=True),
    sa.Column('external_sync_at', sa.Text(), nullable=True),
    sa.Column('goals_json', sa.Text(), nullable=True),
    sa.Column('stakeholders_json', sa.Text(), nullable=True),
    sa.Column('related_project_ids_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_updated_at', 'projects', ['updated_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Text(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('projects_count', sa.Integer(), nullable=True),
    sa.Column('ai_enhanced', sa.Integer(), nullable=True),
    sa.Column('email_sent', sa.Integer(), nullable=True),
    sa.Column('email_sent_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprints',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('capacity_points', sa.Integer(), nullable=True),
    sa.Column('completed_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sprints_project_id', 'sprints', ['project_id'], unique=False)
    op.create_index('idx_sprints_status', 'sprints', ['status'], unique=False)
    op.create_table('ticket_cache',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('assignee', sa.Text(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_seeded_commits',
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('repo_path', sa.Text(), nullable=False),
    sa.Column('seeded_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('hash', 'repo_path')
    )
    op.create_table('voice_synced_items',
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('context_type', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'item_id', 'context_type')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_login', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connected_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('tls_enabled', sa.Integer(), nullable=False),
    sa.Column('workspaces', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('admin_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_used', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_api_keys')
    op.drop_table('connected_clients')
    op.drop_table('audit_log')
    op.drop_table('admin_users')
    op.drop_table('voice_synced_items')
    op.drop_table('voice_seeded_commits')
    op.drop_table('ticket_cache')
    op.drop_index('idx_sprints_status', table_name='sprints')
    op.drop_index('idx_sprints_project_id', table_name='sprints')
    op.drop_table('sprints')
    op.drop_table('reports')
    op.drop_index('idx_projects_updated_at', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_table('pm_update_queue')
    op.drop_table('platform_sync_meta')
    op.drop_table('platform_sync_cache')
    op.drop_table('platform_seen_events')
    op.drop_table('pending_actions')
    op.drop_table('learning_user_profiles')
    op.drop_table('learning_sync_state')
    op.drop_index('idx_learning_samples_email', table_name='learning_samples')
    op.drop_index('idx_learning_samples_context', table_name='learning_samples')
    op.drop_table('learning_samples')
    op.drop_table('learning_consent')
    op.drop_table('client_events')
    op.drop_index('idx_backlog_status', table_name='backlog_items')
    op.drop_index('idx_backlog_sprint_id', table_name='backlog_items')
    op.drop_index('idx_backlog_project_id', table_name='backlog_items')
    op.drop_index('idx_backlog_item_type', table_name='backlog_items')
    op.drop_table('backlog_items')
    # ### end Alembic commands ###
